/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jester (https://sketchfab.com/ImJester)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anchor-69552aac91e94f99a8b1a44d2d80cebc
Title: Anchor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/anchor/scene.gltf')

  return (
    <group {...props} dispose={null}>
      <group position={[0.035, 2.712, -0.011]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Anchor2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Anchor}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Chain}
        position={[0.109, 2.481, -0.03]}
      />
    </group>
  )
}

// This helps preload the model for smoother rendering
useGLTF.preload('/anchor/scene.gltf')
