/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RM02 (https://sketchfab.com/RM02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/container-ship-aaa41cca946b4a08bc08cf692b7757be
Title: Container Ship
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/container_ship/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.452}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[585.693, 633.404, 388.893]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ship_Bridge_0.geometry}
              material={materials.Bridge}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ship_Bridge_0_1.geometry}
              material={materials.Bridge}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ship_Hull_0.geometry}
              material={materials.Hull}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ship_Hull_0_1.geometry}
              material={materials.Hull}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Containers_Containers_0.geometry}
            material={materials.Containers}
            position={[-47.17, 475.961, -412.06]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={102.184}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/container_ship/scene.gltf')